### ISSUE TITLE
Modifier l'actualisation

### ISSUE THREAD

**Issue by Selyjohns** [floman321/prixcarburants#21]
Bonjour,

Merci pour ce super plugin !

Je remarque que les prix ne sont pas mis à jour assez régulièrement (par exemple, vers 10h j'ai les prix de la veille, et si j'actualise, tout se met à jour car les prix ont été modifié entre minuit et 8/9h généralement).

Comment est-ce que je peux modifier le comportement de l'auto update ? Passer en cronHourly peut être mais je ne sais pas comment faire.

Merci d'avance :)

**Comment by floman321** [comment]
Bonjour,

Le cron se fait dans core/class/prixcarburants.class.php
https://github.com/floman321/prixcarburants/blob/db8b3ab3ea9dfe3eb58c7002a6d62d907251373d/core/class/prixcarburants.class.php


Dans la méthode crondaily() a minuit il me semble.


Il faudrait utiliser le cronHourly : 

public static function cronHourly() {
if (date('H') < 14) {
   
		foreach (self::byType('prixcarburants') as $prixcarburants) {
			if ($prixcarburants->getIsEnable() == 1) {
				$cmd = $prixcarburants->getCmd(null, 'refresh');
				if (!is_object($cmd)) {
					continue;
				}
				$cmd->execCmd();
			}
		}


}
}
Code non testé,


Voir cette page : 
https://doc.jeedom.com/fr_FR/dev/tutorial_plugin

C's

**Comment by Bbillyben** [comment]
Salut josselynL

Si tu l'as activé, test la branche béta du jour, elle inclue une configuration avec la définition de la fréquence de rafraichissement du fichiers de prix. (et le support de la 4.2 et le support de commande de geolocalisation dynamique par ailleurs!)

**Comment by Selyjohns** [comment]
Merci pour vos réponses.
Super, quel réactivité haha. J'ai modifié la fréquence de rafraichissement, ça devrait le faire desormais :)

Je remarque aussi que je peux desormais créer des favoris, ce qui n'était pas possible avant (surement à cause de l'incompatibilité 4.2)

Beau travail, merci beaucoup.
