### ISSUE TITLE
Commande contenant uniquement le nom de la station (sans l'adresse)

### ISSUE THREAD

**Issue by Selyjohns** [floman321/prixcarburants#44]
Bonjour,
J'aimerai utiliser uniquement le nom de la station (Intermarché, Leclerc, etc) au lieu de la concaténation nom, adresse de la commande Top X Adresse.
Ce n'est pas très utile pour ma part, on a rarement 2 fois la même station dans les alentours.

Comment puis-je créer une telle commande ?

Merci d'avance.

**Comment by Bbillyben** [comment]
Salut JosselunL,

Là ce n'est pas prévu dans le plugin, le plus simple est d'aller tronquer avec une ligne de script le `top X adresse` jusqu'à la virgule.

tu récupère la valeur dans un bloc code puis un truc du genre : 

```
$cmdValue=cmd::byString('#[objet][sous objet][nom commande]#')->execute();
$str=substr($cmdValue, 0, strpos($cmdValue, ','));
```

puis tu en fait ce que tu veux (dans un virtuel, un message, etc....)



perso, j'habite près d'une grande ville, et j'ai des tonnes de carrefour market, total, auchan et autres stations des même fournisseur dans les zones proches  ;D

**Comment by Selyjohns** [comment]
> Salut JosselunL,
> 
> Là ce n'est pas prévu dans le plugin, le plus simple est d'aller tronquer avec une ligne de script le `top X adresse` jusqu'à la virgule.
> 
> tu récupère la valeur dans un bloc code puis un truc du genre :
> 
> ```
> $cmdValue=cmd::byString('#[objet][sous objet][nom commande]#')->execute();
> $str=substr($cmdValue, 0, strpos($cmdValue, ','));
> ```
> 
> puis tu en fait ce que tu veux (dans un virtuel, un message, etc....)
> 
> perso, j'habite près d'une grande ville, et j'ai des tonnes de carrefour market, total, auchan et autres stations des même fournisseur dans les zones proches ;D

En effet, tout bête !
Merci de ton aide, ça fonctionne à merveille 👍 

```
//identification du scenario
$scenario = scenario::byId(91);

//Récupération du nom de le station + ville (format nom station, ville)
$cmd = cmd::byString("#[Maison][SP95-E10][Top 1 Adresse]#");
$Top1Adresse = $cmd->execCmd();

//Découpage pour n'avoir que la partie avant la virgule
$Top1Station=substr($Top1Adresse, 0, strpos($Top1Adresse, ','));

//Définition de la variable globale
$scenario->setData(Top_1_Station,$Top1Station);
```
