### ISSUE TITLE
prendre en compte les stations "à sec" :)

### ISSUE THREAD

**Issue by phiphila** [floman321/prixcarburants#46]
Bonjour,

Avec les pénuries liées à la grève récentes, mes 3 stations affichées, sur 5 configurées, ne m'affichent plus grand-chose de cohérent, en effet, elles sont configurées pour un affichage par prix.

![image](https://user-images.githubusercontent.com/36555477/196059807-9bb1078a-7e1d-46ac-b7b2-6a67ac73c987.png)
Comme on peut le voir sur l'image, les stations en pénurie affiche "Type de carburant non vendu en station".

Comme on peut le voir sur l'image, les stations en pénurie affichent "Type de carburant non vendu en station".

Est-il possible de prendre en compte les stations affichant "Type de carburant non vendu en station" dans la section "MAJ" comme "Station avec date périmées" pour ne plus les afficher ?

**Comment by Bbillyben** [comment]
Salut, tu peux donner ta configuration.

Je soupçonne que tu as du configurer des stations favorites/fixes, et là, à part afficher ce qu'il y a en station, je ne vois pas trop quoi faire. Si tu as configuré des favoris, c'est que tu veux savoir ce qu'il y a là bas, il me semble normal d'afficher que ce n'est plus disponible!

Si tu configure avec une "date de péremption", ça t'affichera toujours la station, mais avec la mention date obsolète.

**Comment by phiphila** [comment]
Exactement, j'ai des stations favorites/fixes, mais elles sont classées par prix, j'en est 5 en tous mais n'en affiche que 3, les trois première sont affichée, celle au prix le plus bas, alors quand j'ai une station avec le message "Type de carburant non vendu en station", elle est au prix de Zero€ le litre et naturellement placée en top one, j'aimerai qu'elle soit placée en bas de liste et donc ne plus l'afficher

**Comment by Selyjohns** [comment]
Bonjour,
Je venais sur GH exactement pour la même demande.

De mon côté, j'ai 4 stations dans mon rayon, dont 3 en favorites, classement par prix.
Selon moi, le bon sens voudrait que : 

- Entre une station qui a un prix, et une qui n'en a pas, celle qui a un prix soit mieux classée que celle qui n'en a pas
- Que si aucune des stations favorite n'a du carburant disponible, celles qui ont du carburant, et qui se situe dans le rayon (peu importe si favorites ou pas) soient mieux classées.

Voici mon top 4 actuel

#1 
Total Access
on Type de carburant non vendu en station

#2
1.579 €/l
Intermarche
on 20/10/2022

#3
1.602 €/l
Leclerc
on 21/10/2022

#4
1.579 €/l
Carrefour Market
on 20/10/2022

Je trouve que cela n'a pas de sens...
Pourquoi Total est TOP 1 alors que le station est à sec ?
Inter est moins cher, mais les valeurs de Leclerc est plus à jour que Inter et Carrefour...

Je pense qu'il faudrait ajouter un choix : 
- Par prix = prix croissant tant que la date n'est pas considérée comme expirée (mais une station à sec sera toujours derrière celle qui ont du stock)
- Par ordre de selection = les stations s'affichent toujours dans le même ordre (c'est un choix)
- Par pertinence = trouver la bonne formule entre date de màj et disponibilité du carburant

Qu'en pensez-vous ?

**Comment by Bbillyben** [comment]
Salut, 
Oui je comprends le besoin, je ne savais même pas qu'on pouvait faire ça!

note pour les dev : toucher à la fonction de sort devrait le faire  : https://github.com/floman321/prixcarburants/blob/d3eabe774885ffca7e220ed66340b6b33e7fa2de/core/class/prixcarburants.class.php#L950

**Comment by Bbillyben** [comment]
commit https://github.com/floman321/prixcarburants/commit/dddfcfa4b4b8491ca9d8c134d2d841790923767b

devrait régler le problème
